version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '82:80'
    depends_on:
      - backend
    volumes:
      - ./public/resume.pdf:/usr/share/nginx/html/resume.pdf

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - '8081:8080'
