FROM golang:1.22-alpine

WORKDIR /app

# Copy go mod files
COPY go.* ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o main .

EXPOSE 8080

CMD ["./main"] 