FROM golang:1.22-alpine

WORKDIR /app

# Copy the source code
COPY . .

# Download all dependencies
RUN go mod download

# Build the application
RUN go build -o main .

# Expose port 8080
EXPOSE 8080

# Command to run the executable
CMD ["./main"] 